# Generated by Django 5.0.7 on 2024-07-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='duck',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/images/no_image.webp', null=True, upload_to='products/images/'),
        ),
    ]
