# Generated by Django 5.0.7 on 2024-07-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_duck_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='no_image.webp', null=True, upload_to=''),
        ),
    ]
