# Generated by Django 5.0.7 on 2024-07-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/images/no_image.webp', null=True, upload_to='products/images/'),
        ),
    ]
